[package]
name = "rsh"
version = "0.1.0"
authors = ["Adrian Curless <awcurless@wpi.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-signal = "1.1.1"
rustyline = "5.0.3"
rustyline-derive = "0.2.0"
